name: BLS Appointment Checker
run-name: BLS Appointment Checker 🚀
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/6 * * * *'
jobs:
  BLSAppointmentChecker:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: Start Appointments Checker
        run: npm run start --if-present
      - run: echo "🍏 This job's status is ${{ job.status }}."
